### PR TITLE
Laravel translation file support

### PR DESCRIPTION
**Pull request by nicklayb**
Adds following support fixing #44 
- Read .php associative array with either single quote `'` or double quotes strings `"` since laravel uses both using a regular expression
- Serialize file back as double quoted string escaping double qutotes and removing single quote escapes
- `@spec` types specifications in method.

Also includes a basic test.

BTW, Great job on making developments so easy. Contribution in file support are pretty straight forward!

### CODE REVIEW

**Comment by nicklayb** [comment]
Had forgot to run ci-check before pushing :man_facepalming:

My bad, sorry, updated now!

**Comment by nicklayb** [comment]
Due to the regex limitation on parsing nested keys, I started a library to parse associative arrays into elixir's map available at https://github.com/nicklayb/php_assoc_map

At it's current state, the library works but only for one level nested deep.

**Comment by simonprev** [comment]
Nice work! Would it be better to wait for the integration of your lib `php_assoc_map` before adding this to Accent? The integration will remove code in Accent repo so it will be easier to maintain 😄

**Comment by nicklayb** [comment]
Of course! I worked on it all weekend so it can work flawlessly. And I realized that it was not that simple...

It’s almost ready, I also removed references to Laravel since it contains no Laravel specific logic.

Do you prefere to close the PR keep it open until I change for the library?

**Comment by simonprev** [comment]
No we can keep it open until you made your changes 👍

**Comment by nicklayb** [comment]
I've double check, I think it's good!

**Comment by simonprev** [comment]
Everything looks good, but can you rename the format to `Laravel PHP`? Like the `Rails YAML` format, it is tied to the way Laravel parses the file and not a "standard PHP format"

**Comment by nicklayb** [comment]
Has forget two references to Php. It is fixed now and double checked

**Comment by simonprev** [comment]
There are some conflicts in your branch preventing me from merging this, can you ping me back when it is ready? Thank you!

**Comment by nicklayb** [comment]
I don't the conflicts you are talking about neiter in the file changes or the project itself.

I'm up-to-date with master and there is no conflict with. Which one are you talking about?

**Comment by simonprev** [comment]
On my computer, if I pull your branch `laravel` from `git@github.com:nicklayb/accent.git` in the current`master` branch of the repo, there are conflicts.

I tried to resolve them myself but did not know which version to keep from your changes 😕

**Comment by nicklayb** [comment]
New PR #50 made

**Pull request closed without merging**
