### PR TITLE
Add GitLab OAuth provider

### PR DESCRIPTION
**Pull request by bbfdpns**
Adds support for GitLab's OAuth to the login process.

### CODE REVIEW

**Comment by alexanderadam** [comment]
By setting `GITLAB_SITE_URL` it will even be possible to use an own instance?
Is that correct?
That would be great! :raised_hands:

**Comment by simonprev** [comment]
Thanks for the PR, I merged it manually with a small UI fix for the login forms: https://github.com/mirego/accent/commit/c894aca1c47231d8c180fdf44281881ec3c174b4

**Comment by alexanderadam** [comment]
Awesome, thank you @bbfdpns and @simonprev! :raised_hands: 

Any idea when this feature will be available via official Docker release?

**Comment by simonprev** [comment]
[latest](https://hub.docker.com/layers/mirego/accent/latest/images/sha256-91a0e86d7b08a135e0a91dc07a54c2036d52ed8cefb5f180384b7185d9c9bd15?context=explore) and [v1.10.2](https://hub.docker.com/layers/mirego/accent/v1.10.2/images/sha256-c81dff5bac4bc57dbaee17e2aa35369099d8f96b3c22c6e555fd9f9d9e1077d5?context=explore) includes the new provider 🎉

**Pull request closed without merging**
